### ISSUE TITLE
The `mockTestFolder` method copies the content of symlinks in `node_modules` rather than retaining them

### ISSUE THREAD

**Issue by krasiyan** [outbounder/organic-stem-tester#1]
Current the `mockTestFolder` method executes `cp -rL` to copy over the mock stem seed to the temporary folder. The `-L` argument means `always follow symbolic links in SOURCE`. We don't want that since the temp folder most often ends up with `node_modules/organic-stem-skeleton` containing a copy of the stem skeleton (vs being a symlink to it). Newer versions of npm do not allow *directly* having a git repo in `node_modules` and thus we end up with the [`EISGIT`](https://github.com/npm/npm/search?q=EISGIT&type=Issues&utf8=%E2%9C%93) error when trying to apply a stack upgrade. If `node_modules/organic-stem-skeleton` is a symlink this problem is no longer present. IMHO the fastest and easiest solution is to make that possible by changing the `mockTestFolder` method to execute `cp -ra` which would retain the symlinks.

**Comment by outbounder** [comment]
released in v0.2.5
